name: Trigger Remote OBS Services

on:
  push:
  schedule:
    # daily 8:00 UTC+8
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  trigger-osc:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allows other jobs to continue if one fails
      matrix:
        project:
          - '24.03'
          - '24.03:SP1'
          - '24.03:Next'
          - 'master'
        package:
          - 'openjdk-11'
          - 'openjdk-17'
          - 'openjdk-21'
          - 'openjdk-latest'

    steps:
    - name: Install osc
      run: |
        pip install osc

    - name: Set up oscrc credentials
      env:
        OSCRC_CONTENT: ${{ secrets.OBS_PEEWEEP_OSCRC }}
      run: |
        echo "$OSCRC_CONTENT" > .oscrc
        echo "Created .oscrc"

    - name: Trigger OBS Remote Run for ${{ matrix.project }} / ${{ matrix.package }}
      run: |
        osc --config .oscrc service remoterun Factory:RISC-V:OpenJDK:${{ matrix.project }} ${{ matrix.package }}
